name: Release Version

env:
  DOTNET_VERSION: '8.0'

on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: snyk/actions/setup@master

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Run Tests
      run: dotnet test Bank/Bank.WebApi.Test/Bank.WebApi.Test.csproj --logger trx

    - name: Build
      run: dotnet build Bank/Bank.WebApi/Bank.WebApi.csproj -c Release

    - name: Create Release Package
      run: dotnet pack Bank/Bank.WebApi/Bank.WebApi.csproj -c Release -o out

    - name: Publish Release
      uses: softprops/action-gh-release@v1
      with:
        files: out/*.nupkg
